#! /bin/bash

function scan {
  trivy $1
}

images=$(kubectl get "$@" -oyaml | sed -nE 's@[^\w]*image: (.+)@\1@p' | uniq)
while read -r image; do
  DATE=`date +%Y%m%d%h%m%s%ms`
  scan "$image" >> $DATE
done <<< "$images"
